name: Upload Docker images to ghcr.io
on:
  release:
    types: [created]
jobs:
  docker:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Docker meta
        if: github.event_name != 'pull_request'
        run: echo "Done"
        id: meta
