name: Upload Docker images to ghcr.io
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
jobs:
  docker:
    name: Build image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Docker meta
        if: github.event_name != 'pull_request'
        run: echo "Done"
        id: meta
